micronaut:
  application:
    name: tasksManager
netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/tasks_manager`}
    driverClassName: org.postgresql.Driver
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:root}
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
        show_sql: true
